### ISSUE TITLE
Meeting container returns 500 (Internal Server Error)

### ISSUE THREAD

**Issue by belavina** [Seneca-CDOT/ostep-dashboard#16]
```
TypeError: Cannot read property 'filter' of undefined
    at app.get (/usr/src/app/server.js:24:23)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/server.js:10:3
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by poftadeh** [comment]
We should probably create a wiki entry for the room(s) that will replace DB1042, and scrape from there.
