### ISSUE TITLE
Github container failing when commit author is anonymous 

### ISSUE THREAD

**Issue by belavina** [Seneca-CDOT/ostep-dashboard#47]
`author` can appear blank for `singleCommit` when someone commits without valid github user email setup in the github config.

Error message:
```
github            | /usr/src/app/service.js:65
github            |                         singleCommit.author.date = time.toLocaleString("en-US", {timeZone : "America/Toronto"});
github            |                                                  ^
github            | 
github            | TypeError: Cannot set property 'date' of null
github            |     at /usr/src/app/service.js:65:50
github            |     at Array.forEach (<anonymous>)
github            |     at Request._callback (/usr/src/app/service.js:61:34)
github            |     at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
github            |     at Request.emit (events.js:196:13)
github            |     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
github            |     at Request.emit (events.js:196:13)
github            |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
github            |     at Object.onceWrapper (events.js:284:20)
github            |     at IncomingMessage.emit (events.js:201:15)
github            | npm ERR! code ELIFECYCLE
github            | npm ERR! errno 1
github            | npm ERR! github-server@1.0.0 start: `node server.js`
github            | npm ERR! Exit status 1
github            | npm ERR! 
github            | npm ERR! Failed at the github-server@1.0.0 start script.
github            | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
github            | 
github            | npm ERR! A complete log of this run can be found in:
github            | npm ERR!     /root/.npm/_logs/2019-05-23T22_08_28_057Z-debug.log

```

**Comment by manekenpix** [comment]
Should we add the commit to the list, or ignore it?
if added, should it go as 'anonymous', with no date?

**Comment by manekenpix** [comment]
I fixed it, but now when loading Dashboard this happens:
![Screenshot from 2019-05-23 21-36-12](https://user-images.githubusercontent.com/23108901/58296745-f2037e80-7da2-11e9-93d5-d9fe5a892d7e.png)

**Comment by belavina** [comment]
If we are accepting the anonymous commits, then we need to populate all of the `singleCommit` entries (author, repoName etc.):
https://github.com/Seneca-CDOT/ostep-dashboard/blob/master/Github/service.js#L65

I see there's commit author data available under `commit.author` in the json response returned by github, maybe we could use it when `author` is null;
